function [output]=gui_params(paramInit)

name_parameters = {...
    'XY resolution (\mu m)';...
    'Z resolution (\mu m)';...
    'Foci size (pixel)';...
    'Z-slices to skip'; ...
    'Signal name'; ...
    'Low signal'; ...
    'Number of std above mean for spots'; ...
    };

if (isempty(paramInit))
    
    params_default = {...
    '1';...
    '0.2';...
    '2:3';...
    '0';...
    'gfp';...
    'false';...
    '1'};

else
    params_default= paramInit;
end%if

options.Resize='on';
options.WindowsStyle='modal';
options.Interpreter='tex';

output = inputdlg(name_parameters,'NuFoQ parameters', 1, params_default, options);
end
